### ISSUE TITLE
Private key in code

### ISSUE THREAD

**Issue by mattfriend** [alexhuang1117/Data-Science-Portfolio#1]
Hi Alex

I wanted to say, I really like your Data Science Portfolio - very inspiring!

I also wanted to let you know that in the jupyter notebook for the project "FX_Analysis_during_UK_Election", you have included your private keys for the twitter API:
CONSUMER_KEY
CONSUMER_SECRET
ACCESS_TOKEN
ACCESS_TOKEN_SECRET

I'm not an expert, but I understand this is a bad idea - since anyone can now use your private keys and access the twitter API pretending to be you (you may have re-set them by now). Better to create some kind of configuration file that the Jupyter Notebook refers to - but don't load this onto GitHub.

Hope that's useful - please ignore if not - I'm certainly not trying to be any kind of troll!

Best regards,
Matt

**Comment by alexhuang1117** [comment]
Thank you Matt,

I have removed the keys.

Best regards,
Alex
